### PR TITLE
Merge 'develop' to 'master'

### PR DESCRIPTION
**Pull request by CromwellEnage**
Boost.Parameter changes have now been merged from 'develop' to 'master'.

### CODE REVIEW

**Comment by CromwellEnage** [comment]
PR #33 fixes the failing checks.

**Comment by spacelg** [comment]
Hi All,

Could you please merge this fixes into master branch? It failed for a long time.

Thanks,
Lin

**Comment by swatanabe** [comment]
This is currently causing breakage with the beta.  Can we either apply this or (if all else fails) revert the parameter changes for 1.71?

**Comment by lballabio** [comment]
For an example of breakage in the beta, see <https://lists.boost.org/Archives/boost/2019/08/246715.php>.  I tested it with this PR, and it indeed fixes the regression. +1 to merging it before 1.71.

**Comment by ericniebler** [comment]
What's the story with the failing Travis tests?

**Pull request merged**
