### PR TITLE
Reduce the number of MSVC level 4 warnings

### PR DESCRIPTION
**Pull request by sergiud**
This PR fixes several double to float type conversion warnings issued by MSVC.

### CODE REVIEW

**Comment by sergiud** [comment]
@ericniebler Could you please take a look at this PR?

**Comment by sergiud** [comment]
@ericniebler Ping.

**Comment by ldionne** [comment]
@ericniebler @sergiud The PR looks okay to me. I'll merge this in one week unless somebody reacts.

**Comment by ericniebler** [comment]
Merged. Apologies for being unresponsive.

**Pull request merged**
