### PR TITLE
Fix gcc 9 deprecated copy warning.

### PR DESCRIPTION
**Pull request by Romain-Geissler-1A**

### CODE REVIEW

**Comment by Romain-Geissler-1A** [comment]
Ping

**Comment by Romain-Geissler-1A** [comment]
Ping

**Comment by Romain-Geissler-1A** [comment]
@pdimov Have you taken over the maintenance of this library now ?

**Comment by pdimov** [comment]
Can you please rebase on develop to pick up the GHA CI addition?

**Comment by Romain-Geissler-1A** [comment]
Ok I just did.

**Pull request merged**
